version: 0.2

phases:
  install:
   runtime-versions:
     java: openjdk8
   commands:
     - echo Entering install phase...
     - apt-get update -y 
     - apt-get install -y maven
  build:
    commands:
     - echo Build started on `date`
     - mvn clean install
artifacts:
  type: zip
  files:
    - 'target/*.jar'

